pipeline {
    agent any

    environment {
        COMPOSE_FILE = "docker/docker-compose.yml"
    }

    stages {

        stage('Clone') {
            steps {
                echo "Cloning repository..."
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Building Docker images..."
                sh 'docker compose -f $COMPOSE_FILE build'
            }
        }

        stage('Test') {
            parallel {

                stage('Unit Test') {
                    steps {
                        echo "Running unit tests..."
                        sh 'echo Unit tests passed'
                    }
                }

                stage('Lint Check') {
                    steps {
                        echo "Running lint check..."
                        sh 'echo Lint check passed'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Starting containers..."
                sh 'docker compose -f $COMPOSE_FILE up -d'
            }
        }

        stage('Monitoring') {
            steps {
                echo "Checking Pr
