pipeline {
    agent any

    environment {
        BACKEND_IMAGE = "docker-backend"
        FRONTEND_IMAGE = "docker-frontend"
        NAMESPACE = "game"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/raipuryabhawik-collab/ai-zombie-survival.git'
            }
        }

        stage('Show Workspace Debug') {
            steps {
                sh '''
                echo "📂 Current Directory:"
                pwd
                echo "📂 Workspace Files:"
                ls -l
                echo "📂 k8s Folder:"
                ls -l k8s || true
                '''
            }
        }

        stage('Build Backend I

