pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/raipuryabhawik-collab/ai-zombie-survival.git'
            }
        }

        stage('Build') {
            steps {
                sh 'docker compose -f docker/docker-compose.yml build --no-cache'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker compose -f docker/docker-compose.yml up -d'
            }
        }
    }
}

